# Site settings
title: Glutenus Minimus
email: glutenusminimus83@gmail.com
author: "Chloe Barget"
description: Musings of a gluten free glutton
baseurl: "" 
url: "http://www.glutenus-minimus.co.uk"
twitter: G2TheMinimus
github:  
facebook: 

image: apple-touch-icon-180x180.png
# Build settings
markdown: kramdown

permalink: pretty
sass:
    sass_dir: bower_components/foundation/scss
    style: compressed

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - bower.json
    - node_modules/*

